name: petsguide
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  flutter_simple_dependency_injection: ^2.0.0
  flutter_secure_storage: ^7.0.1
  google_sign_in: ^5.4.4
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  carousel_slider: ^4.2.1
  flutter_widget_from_html: ^0.9.1
  flutter_rating_bar: ^4.0.1
  flutter_launcher_icons: ^0.11.0
  cached_network_image: ^3.2.1
  cached_network_image_platform_interface: ^1.0.0
  shared_preferences: ^2.0.17
  flutter_bloc: ^8.1.1
  go_router: ^6.0.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  assets:
    - contents/images/
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "contents/images/logo.png"

 
